services:
  backend:
    build: ./backend
    container_name: StoreTrack-backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: StoreTrack-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

#sudo docker compose up --build